### ISSUE TITLE
Option to randomly cycle comics

### ISSUE THREAD

**Issue by altofctrl** [Blastitt/DailyXKCD#12]
Is it possible to add the option to cycle through random comics on a timer?

**Comment by Blastitt** [comment]
Set the `updateInterval` config option to the number of milliseconds between cycles, and the `randomComic` config option to `true`.

**Comment by whatsnominal** [comment]
The suggested solution doesn't address this issue. `randomComic` only works on days where is no comic. I am happy to work on an enhancement is @Blastitt is ok with this feature - make an option to chose between daily comic vs a random one.
