### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by simonsolberg** [Blastitt/DailyXKCD#14]
Doesn't seem to be working. Nothing shows up on my MagicMirror. I've tried several positions to no avail :/ 

Perhaps the xkcd json has changed? I can't read or write javascript so I can't really help.

**Comment by tisnatch** [comment]
agreed. just re-enabled this after months of not using it and it seems to have broken.

**Comment by simonsolberg** [comment]
after fiddling with this for a while I basically did nothing other than restarting my docker container. works now. weird.

**Comment by ebonak** [comment]
Ah .. too bad, can't get it to work, would be a perfect addition to MM.

**Comment by kwinz** [comment]
I installed this freshly today. And if I add it to my config file the whole MagicMirror doesn't startup up. I only see a completely black screen. If I remove this module it works again.

**Comment by NolanWhitecotton** [comment]
Awesome, thanks!
