### ISSUE TITLE
Change comic size

### ISSUE THREAD

**Issue by mckennajones** [Blastitt/DailyXKCD#6]
Awesome module. Would there be an easy way to add a config option to change the comic size?

Thanks

**Comment by ChristopherMori** [comment]
Any info on this ?

**Comment by Blastitt** [comment]
There's a height config option. Width is based on where you put the module in the Mirror grid.

**Comment by ChristopherMori** [comment]
how do you type out the configurations? I am kind of confused overall with that.... i know its in the config section of that module

`{
    module: 'DailyXKCD',
    position: 'top_right',
    config: {
        invertColors: true,
        title: true,
        altText: false
    }
 },`

**Comment by kewisch** [comment]
```
{ 
  module: 'DailyXKCD', 
  position: 'top_right', 
  config: { 
    invertColors: true, 
    title: true,
    altText: false,
    limitComicHeight: 250
  }
}
```
The default is 450. If you'd like to scale the comic to a different base size that is certainly something else. Shouldn't be too hard to add a config option for this, or fix it with custom css.
