### ISSUE TITLE
XKCD width

### ISSUE THREAD

**Issue by mshain** [Blastitt/DailyXKCD#9]
I have the module installed and place on MagicMirror screen where I want it.  The issue is that no matter where I place it per config.js.  I have looked through the css files and can't seem to locate anywhere there is a .width call out to account for it.

The comic displayed is squished (screenshot attached.)
![screenshot 2017-11-26 21 02 41](https://user-images.githubusercontent.com/1654174/33251701-983d19da-d2ed-11e7-9b38-080dea0ab99e.png)

Mike Shain

**Comment by Blastitt** [comment]
It looks like you may be placing two modules in the same "section". Try putting it in it's own section and see if that works.

**Comment by mshain** [comment]
![screenshot 2017-12-02 09 18 20](https://user-images.githubusercontent.com/1654174/33517978-5e972cd0-d742-11e7-897e-f5cfcac86122.png)
![screenshot 2017-12-02 09 14 16](https://user-images.githubusercontent.com/1654174/33517985-6f3a11ba-d742-11e7-9cfe-7eaf59b1381f.png)

I have the code placed in different areas on the config.js file and the comic still isn't displaying properly.  I have attached screen shots again.

                        module: "alert",
                },
                {
                        module: "updatenotification",
                        position: "top_bar"
                },
                {
                        module: "clock",
                        position: "top_left"
                },
                {
                   module: 'DailyXKCD',
                   position: 'top_left',
                   config: {
                        invertColors: true,
                        title: true,
                        altText: false,
                        randomComic: true
                        }
                },
                {
                        module: "calendar",
                        header: "US Holidays",
                        position: "top_left",
                        config: {
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
                                        }
                                ]
                        }
                },
                {
                   module: 'DailyXKCD',
                   position: 'lower_third',
                   config: {
                        invertColors: true,
                        title: true,
                        altText: false,
                        randomComic: true
                        }
                },
                {
                        module: "compliments",
                        position: "lower_third"
                },
                {
                        module: "currentweather",

**Comment by Blastitt** [comment]
In the first picture, it looks like it's conflicting with the time and calendar module, and in the second it's conflicting with the compliments or newsfeed module. You have to put each module in its own unique position or the spacing is gonna be all messed up.
